import type {
  Asset,
  FeedItem,
  ActivityItem,
  PortfolioHolding,
  Transaction,
  User,
} from "@/types";

// Raw list — exported in shuffled order below so chains are interleaved
const ALL_ASSETS: Asset[] = [
  {
    id: "asset-001",
    name: "Lisbon Commercial Property",
    symbol: "HVST-LCP",
    chain: "mantle" as const,
    category: "real-estate-commercial",
    location: "Lisbon, Portugal",
    country: "Portugal",
    flag: "PT",
    image:
      "https://images.unsplash.com/photo-1565043666747-69f6646db940?w=600&h=300&fit=crop&q=80",
    description:
      "Premium commercial office space in central Lisbon, fully occupied by 3 corporate tenants on 5-year leases. Generates stable rental income with annual rent reviews.",
    annualYieldPercent: 7.2,
    riskScore: 3,
    status: "live",
    totalSupply: 500000,
    pricePerToken: 1.0,
    raiseTarget: 500000,
    raisedAmount: 341000,
    investorCount: 847,
    minInvestment: 1,
    launchDate: new Date(Date.now() - 7 * 86400000).toISOString(),
    closeDate: new Date(Date.now() + 4 * 86400000 + 12 * 3600000).toISOString(),
    nextPayout: new Date(Date.now() + 18 * 86400000).toISOString(),
    assetType: "active_revenue",
    trending: true,
    featured: true,
    ddReport: {
      executiveSummary:
        "Lisbon Commercial Property is a Grade-A office building in central Lisbon generating stable rental income from three corporate tenants. The asset has a strong occupancy history of 97% over 5 years and benefits from Portugal's growing tech and financial services sector.",
      assetDescription:
        "A 4,200m² office complex in Marquês de Pombal, Lisbon's prime business district. Built in 2015, fully renovated in 2021. Currently occupied by a fintech firm, a law practice, and a consulting group, all on 5-year leases with inflation-linked rent reviews.",
      yieldMechanism:
        "Monthly rental income from three corporate tenants is collected by the property management company. After deducting all operating costs, net income is distributed quarterly to token holders in USDC.",
      operatingCostBreakdown:
        "Management fees (8%), maintenance reserve (4%), property insurance (2%), municipal taxes (3%), total deductions: 17% of gross rental income. Net yield to investors: 7.2% annually.",
      risks: [
        {
          name: "Tenant Vacancy Risk",
          description:
            "If a tenant vacates, rental income drops. Mitigated by 5-year lease terms and strong Lisbon office demand.",
          severity: "low",
        },
        {
          name: "Currency Risk",
          description:
            "Rents collected in EUR, distributions in USDC. EUR/USD fluctuation may affect yield in dollar terms.",
          severity: "low",
        },
        {
          name: "Regulatory Risk",
          description:
            "Changes to Portuguese property law or EU regulations could affect operations. Low probability given stable legal environment.",
          severity: "low",
        },
      ],
      riskScore: 3,
      riskScoreJustification:
        "Established revenue stream, blue-chip tenants, stable EU jurisdiction, and strong occupancy history result in a low risk score of 3/10.",
      originatorSummary:
        "PortaVerde Capital, a licensed Portuguese property fund manager with 12 years of operation and €180M AUM across 23 properties.",
      suitableFor: ["conservative", "balanced"],
    },
  },
  {
    id: "asset-002",
    name: "Brazil Solar Energy Fund",
    symbol: "HVST-BSF",
    chain: "mantle" as const,
    category: "infrastructure-energy",
    location: "Minas Gerais, Brazil",
    country: "Brazil",
    flag: "BR",
    image:
      "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&h=300&fit=crop&q=80",
    description:
      "Three utility-scale solar farms totalling 48MW capacity in one of Brazil's sunniest regions. Long-term power purchase agreements with state utility.",
    annualYieldPercent: 11.4,
    riskScore: 5,
    status: "live",
    totalSupply: 1000000,
    pricePerToken: 1.0,
    raiseTarget: 1000000,
    raisedAmount: 788000,
    investorCount: 1342,
    minInvestment: 1,
    launchDate: new Date(Date.now() - 12 * 86400000).toISOString(),
    closeDate: new Date(Date.now() + 2 * 86400000 + 6 * 3600000).toISOString(),
    nextPayout: new Date(Date.now() + 7 * 86400000).toISOString(),
    assetType: "active_revenue",
    trending: true,
    ddReport: {
      executiveSummary:
        "Brazil Solar Energy Fund offers exposure to three operating solar farms with guaranteed revenue via 20-year PPAs. The fund is currently producing 12% above projection due to exceptional solar irradiance this quarter.",
      assetDescription:
        "Three ground-mounted solar PV farms (16MW, 18MW, 14MW) located in Minas Gerais, Brazil. All farms fully operational since 2022. Power sold exclusively to CEMIG under 20-year fixed-price contracts.",
      yieldMechanism:
        "Revenue from electricity sales under PPA contracts. Fixed price per MWh means revenue is predictable regardless of spot market prices.",
      operatingCostBreakdown:
        "O&M contracts (12%), insurance (3%), land lease (2%), management fees (5%), grid connection fees (3%). Total: 25% of gross revenue. Net yield: 11.4% annually.",
      risks: [
        {
          name: "Counterparty Risk (CEMIG)",
          description:
            "Revenue depends on CEMIG honouring PPA contracts. CEMIG is state-owned with strong government backing.",
          severity: "low",
        },
        {
          name: "Technical/Equipment Risk",
          description:
            "Solar panel degradation and inverter failures can reduce output. Fully covered by O&M contracts with performance guarantees.",
          severity: "medium",
        },
        {
          name: "Brazil Political Risk",
          description:
            "Policy changes in Brazil could affect energy sector. Mitigated by long-term fixed contracts.",
          severity: "medium",
        },
        {
          name: "Currency Risk",
          description:
            "Revenue in BRL, distributions in USDC. BRL volatility could affect dollar returns.",
          severity: "medium",
        },
      ],
      riskScore: 5,
      riskScoreJustification:
        "Solid fundamentals with guaranteed revenue, but emerging market currency exposure and political risk in Brazil elevate the score to a medium 5/10.",
      originatorSummary:
        "SolarBridge Renewables, a Brazilian renewable energy developer with 340MW of projects across Latin America.",
      suitableFor: ["balanced", "growth"],
    },
  },
  {
    id: "asset-003",
    name: "Lagos Invoice Finance Pool",
    symbol: "HVST-LIF",
    chain: "mantle" as const,
    category: "business-yield",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    flag: "NG",
    image:
      "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&h=300&fit=crop&q=80",
    description:
      "A revolving pool of short-duration trade invoices from verified Nigerian SMEs. Invoices are pre-screened, insured, and typically mature in 30–90 days.",
    annualYieldPercent: 16.8,
    riskScore: 7,
    status: "live",
    totalSupply: 250000,
    pricePerToken: 1.0,
    raiseTarget: 250000,
    raisedAmount: 201000,
    investorCount: 523,
    minInvestment: 1,
    launchDate: new Date(Date.now() - 3 * 86400000).toISOString(),
    closeDate: new Date(Date.now() + 8 * 86400000).toISOString(),
    nextPayout: new Date(Date.now() + 32 * 86400000).toISOString(),
    assetType: "active_revenue",
    trending: true,
    ddReport: {
      executiveSummary:
        "The Lagos Invoice Finance Pool provides high-yield exposure to Nigerian trade finance. High returns reflect frontier market risk premium. Pool is insured and diversified across 50+ SME debtors.",
      assetDescription:
        "A managed pool of 30–90 day trade finance invoices from pre-vetted Nigerian SMEs in FMCG, construction, and logistics sectors. Pool size: $250,000, revolving structure.",
      yieldMechanism:
        "Invoices purchased at discount, collected at face value. Discount rate averages 14% annualized. Gross yield includes FX premium.",
      operatingCostBreakdown:
        "Credit insurance (4%), management fees (5%), collections costs (2%). Net yield: 16.8% annually.",
      risks: [
        {
          name: "Credit Default Risk",
          description: "SMEs may default on invoices. Pool is insured up to 80% of face value per default.",
          severity: "high",
        },
        {
          name: "Concentration Risk",
          description: "Single-country exposure to Nigeria. Political or economic instability could affect collections.",
          severity: "high",
        },
        {
          name: "Currency Risk", description: "Invoices in NGN, distributions in USDC. NGN is a high-volatility currency.",
          severity: "high",
        },
      ],
      riskScore: 7,
      riskScoreJustification:
        "High yield reflects high risk. Frontier market, currency volatility, and SME credit risk all contribute to a 7/10 risk score. Suitable only for growth investors who understand the risk.",
      originatorSummary:
        "TradeLink Capital, a Lagos-based trade finance platform with $45M in invoices processed since 2020.",
      suitableFor: ["growth"],
    },
  },
  {
    id: "asset-004",
    name: "Dubai Logistics Hub",
    symbol: "HVST-DLH",
    chain: "mantle" as const,
    category: "infrastructure-logistics",
    location: "Dubai, UAE",
    country: "UAE",
    flag: "AE",
    image:
      "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&h=300&fit=crop&q=80",
    description:
      "Modern 12,000m² logistics warehouse near Al Maktoum Airport in Dubai South. Fully leased to two e-commerce fulfilment operators on 7-year terms.",
    annualYieldPercent: 8.9,
    riskScore: 2,
    status: "live",
    totalSupply: 800000,
    pricePerToken: 1.0,
    raiseTarget: 800000,
    raisedAmount: 234000,
    investorCount: 412,
    minInvestment: 1,
    launchDate: new Date(Date.now() - 1 * 86400000).toISOString(),
    closeDate: new Date(Date.now() + 11 * 86400000).toISOString(),
    nextPayout: new Date(Date.now() + 28 * 86400000).toISOString(),
    assetType: "active_revenue",
    featured: true,
    ddReport: {
      executiveSummary:
        "Dubai Logistics Hub is a Grade-A warehouse facility in Dubai's fastest-growing logistics corridor. Near-zero vacancy risk given strong e-commerce growth in the MENA region.",
      assetDescription:
        "12,000m² modern warehouse with 12m clear height, full automation capability, and direct freezone access. Tenants: Noon.com (9,000m²) and a regional 3PL operator (3,000m²).",
      yieldMechanism:
        "Fixed annual rent under 7-year NNN leases. Tenants responsible for all maintenance and insurance. Net to investors: 8.9% annually.",
      operatingCostBreakdown:
        "Management fees (5%), freezone fees (3%), structural insurance (2%). Total: 10% of gross. All other costs tenant-responsible under NNN leases.",
      risks: [
        {
          name: "Geopolitical Risk", description: "UAE is a stable jurisdiction but regional tensions could affect logistics flows.", severity: "low"
        },
        {
          name: "E-commerce Slowdown", description: "If regional e-commerce growth slows, tenant demand could soften at renewal.", severity: "low"
        },
      ],
      riskScore: 2,
      riskScoreJustification:
        "NNN leases with blue-chip tenants, strong UAE legal framework, and booming logistics demand result in a very low risk score of 2/10.",
      originatorSummary:
        "Emirates Industrial REIT, a licensed Dubai real estate investment manager with AED 2.4B in managed assets.",
      suitableFor: ["conservative", "balanced"],
    },
  },
  {
    id: "asset-005",
    name: "Nairobi Student Housing",
    symbol: "HVST-NSH",
    chain: "mantle" as const,
    category: "real-estate-residential",
    location: "Nairobi, Kenya",
    country: "Kenya",
    flag: "KE",
    image:
      "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600&h=300&fit=crop&q=80",
    description:
      "Purpose-built 200-bed student accommodation adjacent to University of Nairobi. Historically 96% occupied with month-by-month leases.",
    annualYieldPercent: 9.4,
    riskScore: 4,
    status: "upcoming",
    totalSupply: 350000,
    pricePerToken: 1.0,
    raiseTarget: 350000,
    raisedAmount: 0,
    investorCount: 0,
    minInvestment: 1,
    launchDate: new Date(Date.now() + 2 * 86400000).toISOString(),
    closeDate: new Date(Date.now() + 14 * 86400000).toISOString(),
    nextPayout: new Date(Date.now() + 45 * 86400000).toISOString(),
    assetType: "active_revenue",
    ddReport: {
      executiveSummary:
        "Nairobi Student Housing offers stable yield from a fully operational student accommodation block with near-full occupancy. Benefits from Kenya's growing university enrollment trend.",
      assetDescription:
        "200 single-occupancy rooms across 4 floors, with shared kitchens, study rooms, and security. Walking distance from University of Nairobi main campus.",
      yieldMechanism:
        "Monthly rent from student tenants. Historically 96% occupied. Rents rise ~8% annually in line with Kenyan CPI.",
      operatingCostBreakdown:
        "Property management (10%), security (5%), utilities (8%), maintenance (5%). Total: 28%. Net yield: 9.4% annually.",
      risks: [
        { name: "Occupancy Risk", description: "Depends on university enrollment levels. Risk is very low given 96% historical occupancy.", severity: "low" },
        { name: "Kenyan Political Risk", description: "Kenya has a history of election-related disruptions which can temporarily affect operations.", severity: "medium" },
      ],
      riskScore: 4,
      riskScoreJustification: "Strong fundamentals with minor emerging-market risk factors resulting in a 4/10 score.",
      originatorSummary: "Savanna Property Fund, a Nairobi-based real estate developer with 15 years of student housing experience.",
      suitableFor: ["balanced", "growth"],
    },
  },
  {
    id: "asset-006",
    name: "Manila Data Centre",
    symbol: "HVST-MDC",
    chain: "mantle" as const,
    category: "infrastructure-logistics",
    location: "Manila, Philippines",
    country: "Philippines",
    flag: "PH",
    image:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=300&fit=crop&q=80",
    description:
      "Tier III data centre in Manila serving regional cloud providers and enterprise clients. 8MW capacity, 92% utilisation, long-term contracts.",
    annualYieldPercent: 13.2,
    riskScore: 5,
    status: "live",
    totalSupply: 600000,
    pricePerToken: 1.0,
    raiseTarget: 600000,
    raisedAmount: 389000,
    investorCount: 678,
    minInvestment: 1,
    launchDate: new Date(Date.now() - 5 * 86400000).toISOString(),
    closeDate: new Date(Date.now() + 6 * 86400000).toISOString(),
    nextPayout: new Date(Date.now() + 22 * 86400000).toISOString(),
    assetType: "active_revenue",
    ddReport: {
      executiveSummary:
        "Manila Data Centre provides high-yield infrastructure exposure to Southeast Asia's fastest-growing digital economy. 92% utilisation and long-term contracts provide revenue stability.",
      assetDescription:
        "8MW Tier III colocation data centre in Pasay City, Manila. Clients include two regional cloud providers and 12 enterprise tenants. Average contract term: 4.2 years.",
      yieldMechanism:
        "Revenue from colocation fees (power + space). Contracts are take-or-pay, providing guaranteed minimum revenue.",
      operatingCostBreakdown:
        "Power costs (35%), maintenance (8%), security (5%), management (5%). Total: 53% of gross. Net yield: 13.2% annually.",
      risks: [
        { name: "Power Cost Inflation", description: "Manila power rates can spike. Some contracts have power pass-through clauses mitigating this risk.", severity: "medium" },
        { name: "Technology Obsolescence", description: "Data centre technology evolves quickly. Capex required for upgrades factored into reserves.", severity: "medium" },
      ],
      riskScore: 5,
      riskScoreJustification: "High yield from growing sector balanced by power cost exposure and Southeast Asian market risk at 5/10.",
      originatorSummary: "PhilDigital Infrastructure, a Manila-based data centre operator with 3 facilities across the Philippines.",
      suitableFor: ["balanced", "growth"],
    },
  },
  {
    id: "asset-007",
    name: "Casablanca Mixed-Use Tower",
    symbol: "HVST-CMT",
    chain: "mantle" as const,
    category: "pre-revenue",
    location: "Casablanca, Morocco",
    country: "Morocco",
    flag: "MA",
    image:
      "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600&h=300&fit=crop&q=80",
    description:
      "Pre-revenue development stage. A 28-floor mixed-use tower under construction in Casablanca's new financial district. Expected completion Q3 2026.",
    annualYieldPercent: 18.5,
    riskScore: 8,
    status: "upcoming",
    totalSupply: 1500000,
    pricePerToken: 0.65,
    raiseTarget: 975000,
    raisedAmount: 0,
    investorCount: 0,
    minInvestment: 1,
    launchDate: new Date(Date.now() + 5 * 86400000).toISOString(),
    closeDate: new Date(Date.now() + 21 * 86400000).toISOString(),
    nextPayout: new Date(Date.now() + 180 * 86400000).toISOString(),
    assetType: "pre_revenue",
    ddReport: {
      executiveSummary:
        "Casablanca Mixed-Use Tower is a high-upside development play in Morocco's fastest-growing commercial district. High projected returns reflect development-stage risk. Not suitable for conservative investors.",
      assetDescription:
        "28-floor tower with 60% commercial, 30% residential, 10% retail. Located in Casa-Finance City. Full planning permission obtained. Construction 18% complete as of listing.",
      yieldMechanism:
        "Post-completion rental income from commercial and residential tenants. Development profit from pre-sold units also flows to token holders.",
      operatingCostBreakdown:
        "Construction cost overrun reserve (10%), management fees (5%), finance costs (8%). Net projected yield post-completion: 18.5% annually.",
      risks: [
        { name: "Construction Risk", description: "Delays or cost overruns could defer yield and erode returns.", severity: "high" },
        { name: "Pre-Revenue Risk", description: "No income until construction completes. Investors wait 12–18 months for first payout.", severity: "high" },
        { name: "Morocco Market Risk", description: "Commercial real estate demand in Casablanca is growing but less established than European markets.", severity: "high" },
      ],
      riskScore: 8,
      riskScoreJustification: "Development-stage asset with construction, pre-revenue, and emerging market risks combines for a high 8/10 score. High upside for growth investors.",
      originatorSummary: "Maghreb Capital Development, a Casablanca-based property developer with 8 completed commercial projects.",
      suitableFor: ["growth"],
    },
  },
  {
    id: "asset-008",
    name: "UK Private Credit Fund",
    symbol: "HVST-UPC",
    chain: "mantle" as const,
    category: "business-yield",
    location: "London, UK",
    country: "United Kingdom",
    flag: "GB",
    image:
      "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600&h=300&fit=crop&q=80",
    description:
      "A diversified pool of senior-secured private credit loans to UK SMEs. FCA-compliant originator, quarterly distributions.",
    annualYieldPercent: 8.1,
    riskScore: 3,
    status: "raise_complete",
    totalSupply: 2000000,
    pricePerToken: 1.0,
    raiseTarget: 2000000,
    raisedAmount: 2000000,
    investorCount: 2341,
    minInvestment: 1,
    launchDate: new Date(Date.now() - 30 * 86400000).toISOString(),
    closeDate: new Date(Date.now() - 2 * 86400000).toISOString(),
    nextPayout: new Date(Date.now() + 5 * 86400000).toISOString(),
    assetType: "active_revenue",
    ddReport: {
      executiveSummary:
        "UK Private Credit Fund is a fully subscribed senior-secured lending pool generating consistent 8.1% annual yield. FCA-regulated originator and diversified loan book make this a low-risk income asset.",
      assetDescription:
        "100 senior-secured loans averaging £20,000 each to UK SMEs in manufacturing, logistics, and professional services. Average loan term: 18 months.",
      yieldMechanism:
        "Interest income from SME loans. Senior secured means assets can be seized in default. Historical default rate: 0.8%.",
      operatingCostBreakdown:
        "Credit management (4%), loan origination (3%), insurance (2%). Net yield: 8.1%.",
      risks: [
        { name: "UK Recession Risk", description: "Economic downturn could increase SME defaults. Mitigated by senior security and diversification.", severity: "low" },
        { name: "Interest Rate Risk", description: "Fixed-rate loans lose relative value if market rates rise significantly.", severity: "low" },
      ],
      riskScore: 3,
      riskScoreJustification: "Senior-secured, FCA-regulated, diversified UK credit at 3/10 risk.",
      originatorSummary: "Meridian Credit Partners, an FCA-authorised UK SME lender with £340M in originations since 2018.",
      suitableFor: ["conservative", "balanced"],
    },
  },
  // ── New assets: Ethereum, BNB, Base, AssetChain ──────────────────────────
  {
    id: "asset-009",
    name: "Sydney Harbour Tower",
    symbol: "HVST-SHT",
    chain: "mantle" as const,
    category: "real-estate-commercial",
    location: "Sydney, Australia",
    country: "Australia",
    flag: "AU",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=300&fit=crop&q=80",
    description: "Grade-A commercial tower overlooking Sydney Harbour. 38 floors, 95% occupied by financial services firms on long-term leases.",
    annualYieldPercent: 6.8,
    riskScore: 2,
    status: "live",
    totalSupply: 1200000,
    pricePerToken: 1.0,
    raiseTarget: 1200000,
    raisedAmount: 540000,
    investorCount: 1023,
    minInvestment: 1,
    launchDate: new Date(Date.now() - 4 * 86400000).toISOString(),
    closeDate: new Date(Date.now() + 9 * 86400000).toISOString(),
    nextPayout: new Date(Date.now() + 21 * 86400000).toISOString(),
    assetType: "active_revenue",
    trending: true,
    ddReport: {
      executiveSummary: "Sydney Harbour Tower is a flagship Grade-A commercial asset in Australia's premier business district with institutional-quality tenants.",
      assetDescription: "38-storey premium office tower in the Sydney CBD. Tenants include two Big-4 banks and a global law firm.",
      yieldMechanism: "Annual rent under NNN leases. AUD rent converted to USDC at quarterly distribution dates.",
      operatingCostBreakdown: "Management (6%), insurance (2%), rates (3%). Net yield: 6.8%.",
      risks: [
        { name: "AUD/USD Currency Risk", description: "AUD weakness can reduce dollar returns.", severity: "low" },
        { name: "Office Demand Shift", description: "Remote work trends may affect long-term demand.", severity: "low" },
      ],
      riskScore: 2,
      riskScoreJustification: "Blue-chip tenants, stable jurisdiction, strong occupancy = 2/10 risk.",
      originatorSummary: "Pacific Realty Trust, a Sydney-based REIT manager with AUD 4.2B in assets.",
      suitableFor: ["conservative", "balanced"],
    },
  },
  {
    id: "asset-010",
    name: "São Paulo Tech Campus",
    symbol: "HVST-STC",
    chain: "mantle" as const,
    category: "real-estate-commercial",
    location: "São Paulo, Brazil",
    country: "Brazil",
    flag: "BR",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=300&fit=crop&q=80",
    description: "Modern tech campus in São Paulo's Faria Lima financial corridor. 3 buildings, 18,000m², leased to leading Brazilian fintech and tech companies.",
    annualYieldPercent: 12.1,
    riskScore: 6,
    status: "live",
    totalSupply: 750000,
    pricePerToken: 1.0,
    raiseTarget: 750000,
    raisedAmount: 290000,
    investorCount: 634,
    minInvestment: 1,
    launchDate: new Date(Date.now() - 6 * 86400000).toISOString(),
    closeDate: new Date(Date.now() + 7 * 86400000).toISOString(),
    nextPayout: new Date(Date.now() + 25 * 86400000).toISOString(),
    assetType: "active_revenue",
    ddReport: {
      executiveSummary: "São Paulo Tech Campus captures Brazil's booming fintech sector with premium office space in the country's financial hub.",
      assetDescription: "Three connected office buildings totalling 18,000m² in Itaim Bibi, São Paulo's prime tech district.",
      yieldMechanism: "Monthly rents from tech tenants on 3-year rolling leases with BRL inflation escalation.",
      operatingCostBreakdown: "Management (8%), maintenance (5%), condominium fees (4%), insurance (2%). Net: 12.1%.",
      risks: [
        { name: "BRL Volatility", description: "Brazilian real depreciation affects USD yield.", severity: "high" },
        { name: "Tech Sector Concentration", description: "Tenant mix is tech-heavy; sector downturns could affect renewals.", severity: "medium" },
      ],
      riskScore: 6,
      riskScoreJustification: "Strong asset but BRL currency risk and tenant concentration push score to 6/10.",
      originatorSummary: "LatamProp, a São Paulo commercial real estate group with R$2.1B under management.",
      suitableFor: ["balanced", "growth"],
    },
  },
  {
    id: "asset-011",
    name: "Singapore Marina Retail",
    symbol: "HVST-SMR",
    chain: "mantle" as const,
    category: "real-estate-commercial",
    location: "Singapore",
    country: "Singapore",
    flag: "SG",
    image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=600&h=300&fit=crop&q=80",
    description: "Premium retail complex along Singapore's Marina Bay waterfront. 8,500m² of luxury retail space with 100% occupancy and international brands.",
    annualYieldPercent: 7.5,
    riskScore: 2,
    status: "live",
    totalSupply: 900000,
    pricePerToken: 1.0,
    raiseTarget: 900000,
    raisedAmount: 412000,
    investorCount: 889,
    minInvestment: 1,
    launchDate: new Date(Date.now() - 8 * 86400000).toISOString(),
    closeDate: new Date(Date.now() + 5 * 86400000).toISOString(),
    nextPayout: new Date(Date.now() + 16 * 86400000).toISOString(),
    assetType: "active_revenue",
    featured: true,
    ddReport: {
      executiveSummary: "Singapore Marina Retail is a premium waterfront retail asset in one of Asia's most stable investment environments.",
      assetDescription: "8,500m² luxury retail space at Marina Bay Sands Boulevard with international luxury brand tenants.",
      yieldMechanism: "Fixed base rent plus turnover rent from retailers. SGD-denominated, converted to USDC quarterly.",
      operatingCostBreakdown: "Management (5%), maintenance (3%), insurance (2%). Net: 7.5%.",
      risks: [
        { name: "Tourism Dependency", description: "Luxury retail heavily influenced by tourist spending levels.", severity: "low" },
      ],
      riskScore: 2,
      riskScoreJustification: "AAA jurisdiction, full occupancy, luxury brand tenants = 2/10 risk.",
      originatorSummary: "MBS Capital Partners, a Singapore-licensed REIT manager with SGD 1.8B in retail assets.",
      suitableFor: ["conservative", "balanced"],
    },
  },
  {
    id: "asset-012",
    name: "New York Carbon Credits",
    symbol: "HVST-NYC",
    chain: "mantle" as const,
    category: "commodities",
    location: "New York, USA",
    country: "USA",
    flag: "US",
    image: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=600&h=300&fit=crop&q=80",
    description: "Verified carbon credit portfolio sourced from RGGI-certified reforestation projects across the US Northeast. Tokenised on Ethereum for transparent provenance.",
    annualYieldPercent: 14.3,
    riskScore: 5,
    status: "upcoming",
    totalSupply: 400000,
    pricePerToken: 1.0,
    raiseTarget: 400000,
    raisedAmount: 0,
    investorCount: 0,
    minInvestment: 1,
    launchDate: new Date(Date.now() + 3 * 86400000).toISOString(),
    closeDate: new Date(Date.now() + 17 * 86400000).toISOString(),
    nextPayout: new Date(Date.now() + 60 * 86400000).toISOString(),
    assetType: "active_revenue",
    ddReport: {
      executiveSummary: "New York Carbon Credits offers exposure to the growing voluntary carbon market via tokenised RGGI-certified offsets with strong institutional demand.",
      assetDescription: "Portfolio of 400,000 verified carbon offsets from 12 reforestation projects in New York, Vermont, and Maine.",
      yieldMechanism: "Income from carbon credit sales to corporate buyers seeking net-zero compliance. Price appreciation from tightening supply.",
      operatingCostBreakdown: "Verification costs (3%), platform fees (2%), management (5%). Net: 14.3%.",
      risks: [
        { name: "Carbon Market Volatility", description: "Carbon credit prices can fluctuate with regulatory changes.", severity: "medium" },
        { name: "Regulatory Risk", description: "RGGI programme changes could affect credit values.", severity: "medium" },
      ],
      riskScore: 5,
      riskScoreJustification: "Regulatory exposure balanced by strong institutional demand and RGGI certification at 5/10.",
      originatorSummary: "GreenVault Americas, a US-registered carbon asset manager with $120M in certified offsets.",
      suitableFor: ["balanced", "growth"],
    },
  },
  {
    id: "asset-013",
    name: "Tokyo Data Infrastructure",
    symbol: "HVST-TDI",
    chain: "mantle" as const,
    category: "infrastructure-logistics",
    location: "Tokyo, Japan",
    country: "Japan",
    flag: "JP",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=300&fit=crop&q=80",
    description: "Tier IV hyperscale data centre in Greater Tokyo, serving Japan's three largest cloud providers. 25MW capacity, 99.99% SLA.",
    annualYieldPercent: 10.7,
    riskScore: 3,
    status: "live",
    totalSupply: 1100000,
    pricePerToken: 1.0,
    raiseTarget: 1100000,
    raisedAmount: 678000,
    investorCount: 1456,
    minInvestment: 1,
    launchDate: new Date(Date.now() - 9 * 86400000).toISOString(),
    closeDate: new Date(Date.now() + 4 * 86400000).toISOString(),
    nextPayout: new Date(Date.now() + 19 * 86400000).toISOString(),
    assetType: "active_revenue",
    trending: true,
    ddReport: {
      executiveSummary: "Tokyo Data Infrastructure is a world-class Tier IV facility with take-or-pay contracts from Japan's leading hyperscale cloud operators.",
      assetDescription: "25MW hyperscale data centre in Yokohama, Greater Tokyo. Clients: SoftBank Cloud, NTT, and Fujitsu Hybrid Cloud.",
      yieldMechanism: "Monthly colocation fees under 7-year take-or-pay contracts. JPY-denominated revenue converted to USDC.",
      operatingCostBreakdown: "Power (30%), maintenance (8%), security (4%), management (5%). Net: 10.7%.",
      risks: [
        { name: "JPY/USD FX Risk", description: "Yen depreciation reduces USD distributions.", severity: "medium" },
        { name: "Power Cost Exposure", description: "Japan power prices are elevated. Partially hedged via fixed-rate contracts.", severity: "medium" },
      ],
      riskScore: 3,
      riskScoreJustification: "Institutional clients, Tier IV reliability, stable Japan jurisdiction = 3/10 risk despite FX exposure.",
      originatorSummary: "NipponDC Holdings, a Tokyo-based data centre operator with 3 facilities and ¥85B in assets.",
      suitableFor: ["conservative", "balanced"],
    },
  },
  {
    id: "asset-014",
    name: "Paris Art & Cultural Fund",
    symbol: "HVST-PAF",
    chain: "mantle" as const,
    category: "commodities",
    location: "Paris, France",
    country: "France",
    flag: "FR",
    image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=600&h=300&fit=crop&q=80",
    description: "A curated portfolio of 42 blue-chip artworks by established European artists. Managed by a Paris-based art fund with expert curation and institutional storage.",
    annualYieldPercent: 9.2,
    riskScore: 5,
    status: "upcoming",
    totalSupply: 500000,
    pricePerToken: 1.0,
    raiseTarget: 500000,
    raisedAmount: 0,
    investorCount: 0,
    minInvestment: 1,
    launchDate: new Date(Date.now() + 4 * 86400000).toISOString(),
    closeDate: new Date(Date.now() + 18 * 86400000).toISOString(),
    nextPayout: new Date(Date.now() + 90 * 86400000).toISOString(),
    assetType: "active_revenue",
    ddReport: {
      executiveSummary: "Paris Art Fund gives retail investors access to the blue-chip art market, historically uncorrelated with equities and delivering consistent appreciation.",
      assetDescription: "42 artworks by established European artists valued at €500,000–€2M each. Stored at Gagosian Paris and Artcurial. Professionally insured and curated.",
      yieldMechanism: "Annual income from art lending to institutions and museums plus appreciation distributed at fund term.",
      operatingCostBreakdown: "Storage and insurance (4%), curation fees (3%), management (5%). Net: 9.2%.",
      risks: [
        { name: "Liquidity Risk", description: "Art is illiquid. Secondary market available but spreads can be wide.", severity: "medium" },
        { name: "Art Market Cyclicality", description: "Blue-chip art markets correlate with ultra-HNW wealth cycles.", severity: "medium" },
      ],
      riskScore: 5,
      riskScoreJustification: "Illiquidity premium compensated by low correlation to traditional markets. 5/10 risk.",
      originatorSummary: "Galerie Patrimoine Capital, a Paris-licensed art investment fund with €80M in managed artworks.",
      suitableFor: ["balanced", "growth"],
    },
  },
  {
    id: "asset-015",
    name: "Lagos Port Energy Terminal",
    symbol: "HVST-LPE",
    chain: "mantle" as const,
    category: "infrastructure-energy",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    flag: "NG",
    image: "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?w=600&h=300&fit=crop&q=80",
    description: "Modern petroleum and LPG distribution terminal at Apapa Port, Lagos. Government-backed offtake agreements with Nigeria's NNPC for 15 years.",
    annualYieldPercent: 19.5,
    riskScore: 8,
    status: "live",
    totalSupply: 600000,
    pricePerToken: 1.0,
    raiseTarget: 600000,
    raisedAmount: 187000,
    investorCount: 344,
    minInvestment: 1,
    launchDate: new Date(Date.now() - 2 * 86400000).toISOString(),
    closeDate: new Date(Date.now() + 13 * 86400000).toISOString(),
    nextPayout: new Date(Date.now() + 30 * 86400000).toISOString(),
    assetType: "active_revenue",
    ddReport: {
      executiveSummary: "Lagos Port Energy Terminal offers frontier-market infrastructure yield with NNPC-backed offtake. High returns reflect Nigeria-specific risk premium.",
      assetDescription: "300,000 barrel petroleum and 15,000-tonne LPG terminal at Apapa Port. NNPC 15-year take-or-pay contract.",
      yieldMechanism: "Fixed throughput fees from NNPC under take-or-pay contract. USD-denominated fees paid monthly.",
      operatingCostBreakdown: "Operations (15%), maintenance (8%), insurance (4%), management (6%). Net: 19.5%.",
      risks: [
        { name: "Nigeria Sovereign Risk", description: "NNPC contract subject to government policy changes.", severity: "high" },
        { name: "Operational Risk", description: "Energy infrastructure carries safety and operational complexity risk.", severity: "high" },
        { name: "NGN Devaluation Risk", description: "Local cost inflation in devalued NGN terms.", severity: "medium" },
      ],
      riskScore: 8,
      riskScoreJustification: "USD contracts mitigate currency risk, but Nigeria sovereign and operational risk score this at 8/10.",
      originatorSummary: "AfriEnergy Infrastructure, a Lagos-based energy logistics group with 3 operational terminals.",
      suitableFor: ["growth"],
    },
  },
  {
    id: "asset-016",
    name: "Miami Residential Portfolio",
    symbol: "HVST-MRP",
    chain: "mantle" as const,
    category: "real-estate-residential",
    location: "Miami, USA",
    country: "USA",
    flag: "US",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&h=300&fit=crop&q=80",
    description: "A portfolio of 34 luxury condominiums in Miami Beach and Brickell. Managed short-term and long-term rental mix optimised for maximum yield.",
    annualYieldPercent: 8.4,
    riskScore: 3,
    status: "live",
    totalSupply: 680000,
    pricePerToken: 1.0,
    raiseTarget: 680000,
    raisedAmount: 315000,
    investorCount: 721,
    minInvestment: 1,
    launchDate: new Date(Date.now() - 5 * 86400000).toISOString(),
    closeDate: new Date(Date.now() + 8 * 86400000).toISOString(),
    nextPayout: new Date(Date.now() + 23 * 86400000).toISOString(),
    assetType: "active_revenue",
    ddReport: {
      executiveSummary: "Miami Residential Portfolio captures Florida's booming luxury rental market with a diversified portfolio of premium condominiums in top Miami neighbourhoods.",
      assetDescription: "34 condominiums averaging 1,200 sqft each across Brickell (20 units) and Miami Beach (14 units). Managed by a licensed Florida property manager.",
      yieldMechanism: "Blended income from short-term (Airbnb/VRBO) and long-term rentals. Portfolio manager optimises mix seasonally.",
      operatingCostBreakdown: "Management (12%), HOA fees (6%), insurance (3%), maintenance (4%). Net: 8.4%.",
      risks: [
        { name: "Hurricane Risk", description: "Florida properties exposed to hurricane season. Full insurance coverage maintained.", severity: "medium" },
        { name: "Short-term Regulation Risk", description: "Cities may restrict STR licences. Long-term fallback maintained.", severity: "low" },
      ],
      riskScore: 3,
      riskScoreJustification: "USD income, strong Miami market, diversified rental strategy = 3/10 risk.",
      originatorSummary: "SunState Capital, a Miami-based residential property fund with $290M in managed condominiums.",
      suitableFor: ["conservative", "balanced"],
    },
  },
  {
    id: "asset-017",
    name: "Accra Gold Royalty Fund",
    symbol: "HVST-AGR",
    chain: "mantle" as const,
    category: "commodities",
    location: "Accra, Ghana",
    country: "Ghana",
    flag: "GH",
    image: "https://images.unsplash.com/photo-1610375461249-63c7d2d8f2a9?w=600&h=300&fit=crop&q=80",
    description: "Royalty interest in three producing gold mines in Ghana's Ashanti Belt. USD-denominated royalties, paid quarterly based on gold production volume.",
    annualYieldPercent: 15.6,
    riskScore: 6,
    status: "live",
    totalSupply: 450000,
    pricePerToken: 1.0,
    raiseTarget: 450000,
    raisedAmount: 198000,
    investorCount: 412,
    minInvestment: 1,
    launchDate: new Date(Date.now() - 3 * 86400000).toISOString(),
    closeDate: new Date(Date.now() + 10 * 86400000).toISOString(),
    nextPayout: new Date(Date.now() + 35 * 86400000).toISOString(),
    assetType: "active_revenue",
    ddReport: {
      executiveSummary: "Accra Gold Royalty Fund provides USD-denominated exposure to Ghana's world-class gold mining sector via pre-negotiated royalty agreements.",
      assetDescription: "Net smelter return royalties on three producing gold mines in the Ashanti Belt. Combined annual production: ~120,000 oz. Royalty rate: 2.5% NSR.",
      yieldMechanism: "Quarterly royalty payments based on gold production × spot gold price × 2.5% NSR rate.",
      operatingCostBreakdown: "Administration (3%), legal/compliance (2%), management (4%). Net: 15.6%.",
      risks: [
        { name: "Gold Price Risk", description: "Royalty income rises and falls with spot gold price.", severity: "medium" },
        { name: "Ghana Mining Risk", description: "Operational, political, and environmental risks at mine level.", severity: "high" },
      ],
      riskScore: 6,
      riskScoreJustification: "Gold price upside potential offset by frontier market mining risks = 6/10.",
      originatorSummary: "AfriGold Royalties, a Ghana-registered royalty aggregator with 7 active royalty agreements.",
      suitableFor: ["balanced", "growth"],
    },
  },
  {
    id: "asset-018",
    name: "Barcelona Hotel & Leisure",
    symbol: "HVST-BHL",
    chain: "mantle" as const,
    category: "real-estate-commercial",
    location: "Barcelona, Spain",
    country: "Spain",
    flag: "ES",
    image: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=600&h=300&fit=crop&q=80",
    description: "A 4-star boutique hotel with 120 rooms in Barcelona's Gothic Quarter. Consistently 88% occupied year-round with strong summer peaks.",
    annualYieldPercent: 10.3,
    riskScore: 4,
    status: "live",
    totalSupply: 550000,
    pricePerToken: 1.0,
    raiseTarget: 550000,
    raisedAmount: 243000,
    investorCount: 567,
    minInvestment: 1,
    launchDate: new Date(Date.now() - 7 * 86400000).toISOString(),
    closeDate: new Date(Date.now() + 6 * 86400000).toISOString(),
    nextPayout: new Date(Date.now() + 27 * 86400000).toISOString(),
    assetType: "active_revenue",
    ddReport: {
      executiveSummary: "Barcelona Hotel offers hospitality-sector exposure in Europe's top tourist destination with strong year-round bookings and proven management.",
      assetDescription: "120-room 4-star boutique hotel, Casa Meridian, in the Gothic Quarter. Average ADR €185. TripAdvisor rating 4.7/5.",
      yieldMechanism: "Net hotel operating income distributed quarterly. Summer ADR premium significantly lifts annual returns.",
      operatingCostBreakdown: "Staff (35%), F&B costs (12%), maintenance (6%), management (8%). Net: 10.3%.",
      risks: [
        { name: "Tourism Cyclicality", description: "Hotel performance tied to travel demand. COVID showed extreme downside scenario.", severity: "medium" },
        { name: "Barcelona Regulation", description: "City may tighten hotel licensing. Existing licence grandfathered.", severity: "low" },
      ],
      riskScore: 4,
      riskScoreJustification: "Strong performance history in Europe's most visited city. Tourism risk keeps score at 4/10.",
      originatorSummary: "Iberian Hospitality Partners, a Barcelona-based hotel operator with 8 properties across Spain.",
      suitableFor: ["balanced", "growth"],
    },
  },
  {
    id: "asset-019",
    name: "Abu Dhabi Green Bond",
    symbol: "HVST-AGB",
    chain: "mantle" as const,
    category: "business-yield",
    location: "Abu Dhabi, UAE",
    country: "UAE",
    flag: "AE",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=300&fit=crop&q=80",
    description: "AAA-rated green sovereign bond issued by Abu Dhabi's Department of Finance. Proceeds fund renewable energy and sustainable infrastructure in the UAE.",
    annualYieldPercent: 5.8,
    riskScore: 1,
    status: "live",
    totalSupply: 3000000,
    pricePerToken: 1.0,
    raiseTarget: 3000000,
    raisedAmount: 2100000,
    investorCount: 4231,
    minInvestment: 1,
    launchDate: new Date(Date.now() - 14 * 86400000).toISOString(),
    closeDate: new Date(Date.now() + 3 * 86400000).toISOString(),
    nextPayout: new Date(Date.now() + 14 * 86400000).toISOString(),
    assetType: "active_revenue",
    featured: true,
    ddReport: {
      executiveSummary: "Abu Dhabi Green Bond is the lowest-risk asset on the platform — a AAA-rated sovereign instrument from one of the world's wealthiest governments.",
      assetDescription: "Tokenised tranche of the Abu Dhabi Department of Finance 2030 Green Bond. Coupon: 5.8% p.a. Rated AAA/Aaa by S&P/Moody's.",
      yieldMechanism: "Fixed semi-annual coupon payments converted to USDC at payment date.",
      operatingCostBreakdown: "Tokenisation platform fee (0.5%), custodian (0.3%), management (0.4%). Net: 5.8%.",
      risks: [
        { name: "Sovereign Risk", description: "Effectively zero — Abu Dhabi has USD 1T+ sovereign wealth fund backing.", severity: "low" },
      ],
      riskScore: 1,
      riskScoreJustification: "AAA sovereign, USD-pegged economy, massive SWF backing = lowest possible risk of 1/10.",
      originatorSummary: "Abu Dhabi Department of Finance, issuer of the 2030 Sustainability Sukuk.",
      suitableFor: ["conservative", "balanced"],
    },
  },
  {
    id: "asset-020",
    name: "Bogota Transit Infrastructure",
    symbol: "HVST-BTI",
    chain: "mantle" as const,
    category: "infrastructure-logistics",
    location: "Bogota, Colombia",
    country: "Colombia",
    flag: "CO",
    image: "https://images.unsplash.com/photo-1558618047-3c8c69c58a84?w=600&h=300&fit=crop&q=80",
    description: "Revenue-sharing stake in Bogota's TransMilenio BRT expansion. Government-backed concession, USD-denominated revenue, 20-year term.",
    annualYieldPercent: 13.8,
    riskScore: 6,
    status: "upcoming",
    totalSupply: 800000,
    pricePerToken: 1.0,
    raiseTarget: 800000,
    raisedAmount: 0,
    investorCount: 0,
    minInvestment: 1,
    launchDate: new Date(Date.now() + 1 * 86400000).toISOString(),
    closeDate: new Date(Date.now() + 15 * 86400000).toISOString(),
    nextPayout: new Date(Date.now() + 50 * 86400000).toISOString(),
    assetType: "active_revenue",
    ddReport: {
      executiveSummary: "Bogota Transit Infrastructure offers infrastructure yield from Colombia's largest public transit expansion, backed by a government concession agreement.",
      assetDescription: "Revenue-share concession covering 3 new TransMilenio BRT corridors in northern Bogota. Daily ridership projection: 180,000 passengers by Year 2.",
      yieldMechanism: "Concession revenue share based on fare collection. USD-indexed tariff adjustment mechanism in the concession agreement.",
      operatingCostBreakdown: "Operations (18%), maintenance (10%), management (5%). Net: 13.8%.",
      risks: [
        { name: "Ridership Risk", description: "Revenue depends on actual passenger volumes reaching projections.", severity: "medium" },
        { name: "Colombia Political Risk", description: "Government policy changes could affect concession terms.", severity: "high" },
      ],
      riskScore: 6,
      riskScoreJustification: "Government-backed with USD indexing but Colombia political risk and ridership uncertainty = 6/10.",
      originatorSummary: "AndeanInfra Group, a Bogota-based infrastructure developer with 4 operational transit concessions.",
      suitableFor: ["balanced", "growth"],
    },
  },
];

// Shuffled: mantle, solana, ethereum, bnb, base, assetchain interleaved
const SHUFFLED_ORDER = [
  "asset-001", // mantle   – Lisbon
  "asset-003", // solana   – Lagos Invoice
  "asset-009", // ethereum – Sydney Harbour
  "asset-010", // bnb      – São Paulo Tech
  "asset-011", // base     – Singapore Marina
  "asset-013", // assetchain – Tokyo Data
  "asset-002", // mantle   – Brazil Solar
  "asset-005", // solana   – Nairobi Student
  "asset-012", // ethereum – NY Carbon Credits
  "asset-016", // bnb      – Miami Residential
  "asset-014", // base     – Paris Art Fund
  "asset-015", // assetchain – Lagos Port Energy
  "asset-004", // mantle   – Dubai Logistics
  "asset-017", // ethereum – Accra Gold
  "asset-020", // bnb      – Bogota Transit
  "asset-018", // base     – Barcelona Hotel
  "asset-019", // assetchain – Abu Dhabi Bond
  "asset-007", // mantle   – Casablanca Tower
  "asset-006", // solana   – Manila Data Centre
  "asset-008", // mantle   – UK Credit Fund
];

export const MOCK_ASSETS: Asset[] = SHUFFLED_ORDER.map(
  (id) => ALL_ASSETS.find((a) => a.id === id)!
);

export const MOCK_TICKER_ITEMS = [
  { id: "t1", color: "green", address: "0x4f2a...8b1c", type: "BOUGHT", asset: "Lisbon Property", amount: "$250" },
  { id: "t2", color: "amber", address: "0x7c3d...2e9f", type: "LAUNCHED", asset: "Nairobi Housing", amount: "LIVE" },
  { id: "t3", color: "green", address: "0x1a8b...5d4e", type: "BOUGHT", asset: "Brazil Solar", amount: "$1,200" },
  { id: "t4", color: "blue", address: "0x9e2f...7a3c", type: "YIELD", asset: "UK Credit Fund", amount: "$34.20" },
  { id: "t5", color: "green", address: "0x3b7c...1f8a", type: "BOUGHT", asset: "Dubai Logistics", amount: "$500" },
  { id: "t6", color: "green", address: "0x5d1e...9c2b", type: "BOUGHT", asset: "Lagos Invoice", amount: "$100" },
  { id: "t7", color: "amber", address: "0x8f4a...6d1e", type: "MILESTONE", asset: "Brazil Solar", amount: "75% raised" },
  { id: "t8", color: "green", address: "0x2c9b...3a7f", type: "BOUGHT", asset: "Manila Data Centre", amount: "$300" },
  { id: "t9", color: "blue", address: "0x6e3d...4b2c", type: "YIELD", asset: "Brazil Solar", amount: "$128.40" },
  { id: "t10", color: "green", address: "0x4a1f...8e3d", type: "BOUGHT", asset: "Lisbon Property", amount: "$750" },
];

export const MOCK_ACTIVITY: ActivityItem[] = [
  {
    id: "a1",
    eventType: "LAUNCHED",
    headline: "Dubai Logistics Hub just went LIVE",
    subtitle: "8.9% APY · UAE · $800K raise",
    createdAt: new Date(Date.now() - 2 * 60000),
    assetId: "asset-004",
  },
  {
    id: "a2",
    eventType: "INVESTED",
    headline: "Someone invested $1,200 in Brazil Solar",
    subtitle: "78.8% raised · 2d 6h left",
    createdAt: new Date(Date.now() - 4 * 60000),
    assetId: "asset-002",
  },
  {
    id: "a3",
    eventType: "YIELD",
    headline: "UK Credit Fund distributed $4,280",
    subtitle: "$0.041/token · 2,341 holders",
    createdAt: new Date(Date.now() - 8 * 60000),
    assetId: "asset-008",
  },
  {
    id: "a4",
    eventType: "MILESTONE",
    headline: "Brazil Solar hit 75% subscribed",
    subtitle: "$750,000 raised of $1,000,000",
    createdAt: new Date(Date.now() - 15 * 60000),
    assetId: "asset-002",
  },
  {
    id: "a5",
    eventType: "INVESTED",
    headline: "Someone invested $500 in Lisbon Property",
    subtitle: "68.2% raised · 4d 12h left",
    createdAt: new Date(Date.now() - 22 * 60000),
    assetId: "asset-001",
  },
  {
    id: "a6",
    eventType: "INVESTED",
    headline: "Someone invested $300 in Manila Data",
    subtitle: "64.8% raised · 6d left",
    createdAt: new Date(Date.now() - 35 * 60000),
    assetId: "asset-006",
  },
  {
    id: "a7",
    eventType: "COMPLETE",
    headline: "UK Private Credit Fund FULLY SUBSCRIBED",
    subtitle: "$2,000,000 raised · 2,341 investors",
    createdAt: new Date(Date.now() - 2 * 86400000),
    assetId: "asset-008",
  },
  {
    id: "a8",
    eventType: "INVESTED",
    headline: "Someone invested $100 in Lagos Invoice",
    subtitle: "80.4% raised · 8d left",
    createdAt: new Date(Date.now() - 48 * 60000),
    assetId: "asset-003",
  },
];

export const MOCK_FEED_ITEMS: FeedItem[] = [
  {
    id: "f1",
    eventType: "ASSET_LIVE",
    assetId: "asset-004",
    assetName: "Dubai Logistics Hub",
    metadata: { yieldPercent: 8.9, raisedPercent: 29.2, daysLeft: 11 },
    createdAt: new Date(Date.now() - 2 * 60000),
  },
  {
    id: "f2",
    eventType: "INVESTMENT_MADE",
    assetId: "asset-002",
    assetName: "Brazil Solar Energy Fund",
    metadata: { amount: 1200, raisedPercent: 78.8 },
    createdAt: new Date(Date.now() - 4 * 60000),
  },
  {
    id: "f3",
    eventType: "RAISE_MILESTONE",
    assetId: "asset-002",
    assetName: "Brazil Solar Energy Fund",
    metadata: { milestone: 75, raised: 750000, target: 1000000 },
    createdAt: new Date(Date.now() - 15 * 60000),
  },
  {
    id: "f4",
    eventType: "YIELD_DISTRIBUTED",
    assetId: "asset-008",
    assetName: "UK Private Credit Fund",
    metadata: { totalYield: 4280, holderCount: 2341, perToken: 0.041 },
    createdAt: new Date(Date.now() - 8 * 60000),
  },
  {
    id: "f5",
    eventType: "UPCOMING_LAUNCH",
    assetId: "asset-005",
    assetName: "Nairobi Student Housing",
    metadata: { daysToLaunch: 2, waitlistCount: 412, yieldPercent: 9.4 },
    createdAt: new Date(Date.now() - 30 * 60000),
  },
];

export const MOCK_PORTFOLIO: PortfolioHolding[] = [
  {
    assetId: "asset-001",
    assetName: "Lisbon Commercial Property",
    assetImage: "https://images.unsplash.com/photo-1565043666747-69f6646db940?w=400&h=200&fit=crop&q=80",
    category: "real-estate-commercial",
    tokens: 2500,
    currentValue: 2500,
    purchaseValue: 2500,
    yieldEarned: 180.00,
    annualYieldPercent: 7.2,
    nextPayout: new Date(Date.now() + 18 * 86400000).toISOString(),
  },
  {
    assetId: "asset-002",
    assetName: "Brazil Solar Energy Fund",
    assetImage: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400&h=200&fit=crop&q=80",
    category: "infrastructure-energy",
    tokens: 5000,
    currentValue: 5120,
    purchaseValue: 5000,
    yieldEarned: 570.00,
    annualYieldPercent: 11.4,
    nextPayout: new Date(Date.now() + 7 * 86400000).toISOString(),
  },
  {
    assetId: "asset-008",
    assetName: "UK Private Credit Fund",
    assetImage: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=400&h=200&fit=crop&q=80",
    category: "business-yield",
    tokens: 1500,
    currentValue: 1500,
    purchaseValue: 1500,
    yieldEarned: 121.50,
    annualYieldPercent: 8.1,
    nextPayout: new Date(Date.now() + 5 * 86400000).toISOString(),
  },
  {
    assetId: "asset-004",
    assetName: "Dubai Logistics Hub",
    assetImage: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&h=200&fit=crop&q=80",
    category: "infrastructure-logistics",
    tokens: 1000,
    currentValue: 1000,
    purchaseValue: 1000,
    yieldEarned: 44.50,
    annualYieldPercent: 8.9,
    nextPayout: new Date(Date.now() + 28 * 86400000).toISOString(),
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: "tx1",
    type: "investment",
    description: "Invested in Brazil Solar Energy Fund",
    amount: -500,
    currency: "USDC",
    status: "confirmed",
    createdAt: new Date(Date.now() - 12 * 86400000),
    txHash: "0x4f2a8b1c3e5d7f9a2c4e6b8d0f1a3c5e7b9d",
  },
  {
    id: "tx2",
    type: "yield",
    description: "Yield from UK Private Credit Fund",
    amount: 5.60,
    currency: "USDC",
    status: "confirmed",
    createdAt: new Date(Date.now() - 7 * 86400000),
  },
  {
    id: "tx3",
    type: "deposit",
    description: "P2P deposit via M-Pesa",
    amount: 200,
    currency: "USDC",
    status: "confirmed",
    createdAt: new Date(Date.now() - 14 * 86400000),
  },
  {
    id: "tx4",
    type: "investment",
    description: "Invested in Lisbon Commercial Property",
    amount: -250,
    currency: "USDC",
    status: "confirmed",
    createdAt: new Date(Date.now() - 10 * 86400000),
  },
  {
    id: "tx5",
    type: "yield",
    description: "Yield from Brazil Solar Energy Fund",
    amount: 34.20,
    currency: "USDC",
    status: "confirmed",
    createdAt: new Date(Date.now() - 3 * 86400000),
  },
];

export const MOCK_USER: User = {
  id: "user-001",
  name: "Alex Johnson",
  email: "alex@example.com",
  walletAddress: "0x4f2a8b1c3e5d7f9a2c4e6b8d0f1a3c5e",
  balance: 487.50,
  kycTier: 1,
  kycStatus: "approved",
  investorProfile: {
    investmentPreference: "mixed",
    holdDuration: "medium",
    riskAppetite: "balanced",
  },
};

export const CATEGORY_LABELS: Record<string, string> = {
  "real-estate-commercial": "Real Estate · Commercial",
  "real-estate-residential": "Real Estate · Residential",
  "infrastructure-energy": "Infrastructure · Energy",
  "infrastructure-logistics": "Infrastructure · Logistics",
  "business-yield": "Business Yield",
  "commodities": "Commodities",
  "pre-revenue": "Pre-Revenue",
};

// CATEGORY_ICONS is kept for legacy reference; use CategoryIcon component for rendering
export const CATEGORY_ICONS: Record<string, string> = {
  "real-estate-commercial": "Building2",
  "real-estate-residential": "Home",
  "infrastructure-energy": "Zap",
  "infrastructure-logistics": "Factory",
  "business-yield": "TrendingUp",
  "commodities": "Wheat",
  "pre-revenue": "Rocket",
};
